name: Publish

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+**"]

jobs:

  publish:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'corretto'

    - uses: olegtarasov/get-tag@v2.1
      id: tagName
      with:
        tagRegex: "v(.*)"

    - name: Publish Maven
      uses: burrunan/gradle-cache-action@v1
      env:
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_SIGNING_KEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
      with:
        job-id: jdk8-build-test
        arguments: >-
          build
          publishRelease
          -x test
        properties: |
          releaseVersion=${{ steps.tagName.outputs.tag }}
          ossrhUsername=${{ secrets.OSSRH_USERNAME }}
          ossrhPassword=${{ secrets.OSSRH_PASSWORD }}
